import { useEffect, useState } from "react";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
  DialogFooter,
} from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import type { GeneratedDocument } from "@/lib/types";
import { store } from "@/lib/store";
import { downloadDocAsPdf } from "@/lib/pdf";
import { Download, Save, Trash2 } from "lucide-react";
import { toast } from "sonner";

interface Props {
  document: GeneratedDocument | null;
  open: boolean;
  onOpenChange: (open: boolean) => void;
}

export function DocumentEditorDialog({ document, open, onOpenChange }: Props) {
  const [content, setContent] = useState("");
  const [tab, setTab] = useState<"edit" | "preview">("preview");

  useEffect(() => {
    if (document) {
      setContent(document.content);
      setTab("preview");
    }
  }, [document]);

  if (!document) return null;

  const handleSave = () => {
    store.updateDocument(document.id, content);
    toast.success("Saved changes");
  };

  const handleDownload = () => {
    downloadDocAsPdf({ ...document, content });
    toast.success("PDF downloaded");
  };

  const handleDelete = () => {
    store.removeDocument(document.id);
    onOpenChange(false);
    toast("Document removed");
  };

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="max-w-3xl max-h-[90vh] flex flex-col">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            {document.title}
            <span className="text-xs font-normal text-muted-foreground">v{document.version}</span>
          </DialogTitle>
          <DialogDescription>
            Generated by AI based on your profile and the job description. Edit before downloading.
          </DialogDescription>
        </DialogHeader>

        <div className="flex items-center gap-1 border-b">
          <button
            className={`px-3 py-2 text-sm font-medium border-b-2 transition-colors ${
              tab === "preview" ? "border-primary text-primary" : "border-transparent text-muted-foreground"
            }`}
            onClick={() => setTab("preview")}
          >
            Preview
          </button>
          <button
            className={`px-3 py-2 text-sm font-medium border-b-2 transition-colors ${
              tab === "edit" ? "border-primary text-primary" : "border-transparent text-muted-foreground"
            }`}
            onClick={() => setTab("edit")}
          >
            Edit
          </button>
        </div>

        <div className="flex-1 overflow-auto">
          {tab === "preview" ? (
            <div className="prose prose-sm max-w-none p-2">
              <pre className="whitespace-pre-wrap font-sans text-sm leading-relaxed bg-muted/30 rounded-lg p-5 border">
                {content}
              </pre>
            </div>
          ) : (
            <Textarea
              value={content}
              onChange={(e) => setContent(e.target.value)}
              className="font-mono text-xs min-h-[55vh] resize-none"
            />
          )}
        </div>

        <DialogFooter className="flex-row sm:justify-between gap-2">
          <Button variant="ghost" size="sm" onClick={handleDelete}>
            <Trash2 className="h-4 w-4" /> Delete
          </Button>
          <div className="flex gap-2">
            {tab === "edit" && (
              <Button variant="outline" size="sm" onClick={handleSave}>
                <Save className="h-4 w-4" /> Save
              </Button>
            )}
            <Button size="sm" onClick={handleDownload} className="bg-gradient-primary text-primary-foreground hover:opacity-95">
              <Download className="h-4 w-4" /> Download PDF
            </Button>
          </div>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
