import { useEffect, useMemo, useState } from "react";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
  DialogFooter,
} from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import type { GeneratedDocument } from "@/lib/types";
import { store } from "@/lib/store";
import { downloadDocAsPdf } from "@/lib/pdf";
import { Download, Save, Trash2 } from "lucide-react";
import { toast } from "sonner";
import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";
import remarkBreaks from "remark-breaks";
import { prepareMarkdownForPreview } from "@/lib/markdownPreview";

interface Props {
  document: GeneratedDocument | null;
  open: boolean;
  onOpenChange: (open: boolean) => void;
  /** When false, job one-time documents can only be edited, not removed. */
  allowDelete?: boolean;
}

export function DocumentEditorDialog({ document, open, onOpenChange, allowDelete = true }: Props) {
  const [content, setContent] = useState("");
  const [tab, setTab] = useState<"edit" | "preview">("preview");

  useEffect(() => {
    if (document) {
      setContent(document.content);
      setTab("preview");
    }
  }, [document]);

  const previewMarkdown = useMemo(() => prepareMarkdownForPreview(content), [content]);

  if (!document) return null;

  const handleSave = () => {
    void store.updateDocument(document.id, content).then(
      () => toast.success("Saved changes"),
      (e) => toast.error(e instanceof Error ? e.message : "Save failed"),
    );
  };

  const handleDownload = () => {
    downloadDocAsPdf({ ...document, content });
    toast.success("PDF downloaded");
  };

  const handleDelete = () => {
    void store.removeDocument(document.id).then(
      () => {
        onOpenChange(false);
        toast("Document removed");
      },
      (e) => toast.error(e instanceof Error ? e.message : "Delete failed"),
    );
  };

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="max-w-3xl max-h-[90vh] flex flex-col">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            {document.title}
            <span className="text-xs font-normal text-muted-foreground">v{document.version}</span>
          </DialogTitle>
          <DialogDescription>
            Generated by AI based on your profile and the job description. Edit before downloading.
          </DialogDescription>
        </DialogHeader>

        <div className="flex items-center gap-1 border-b">
          <button
            className={`px-3 py-2 text-sm font-medium border-b-2 transition-colors ${
              tab === "preview" ? "border-primary text-primary" : "border-transparent text-muted-foreground"
            }`}
            onClick={() => setTab("preview")}
          >
            Preview
          </button>
          <button
            className={`px-3 py-2 text-sm font-medium border-b-2 transition-colors ${
              tab === "edit" ? "border-primary text-primary" : "border-transparent text-muted-foreground"
            }`}
            onClick={() => setTab("edit")}
          >
            Edit
          </button>
        </div>

        <div className="flex-1 overflow-auto">
          {tab === "preview" ? (
            <div className="rounded-lg border bg-muted/30 p-5 min-h-[40vh] text-foreground">
              <div
                className="prose prose-sm dark:prose-invert max-w-none
                  prose-headings:font-display prose-headings:font-semibold
                  prose-p:leading-relaxed prose-li:my-0.5
                  prose-h1:text-2xl prose-h2:text-lg prose-h3:text-base
                  [&>*:first-child]:mt-0"
              >
                <ReactMarkdown remarkPlugins={[remarkGfm, remarkBreaks]}>{previewMarkdown}</ReactMarkdown>
              </div>
            </div>
          ) : (
            <Textarea
              value={content}
              onChange={(e) => setContent(e.target.value)}
              className="font-mono text-xs min-h-[55vh] resize-none"
            />
          )}
        </div>

        <DialogFooter className="flex-row sm:justify-between gap-2">
          {allowDelete ? (
            <Button variant="ghost" size="sm" onClick={handleDelete}>
              <Trash2 className="h-4 w-4" /> Delete
            </Button>
          ) : (
            <span className="text-xs text-muted-foreground self-center max-w-[14rem]">
              This document is a one-time generation for a job. Edit the text, or use Download.
            </span>
          )}
          <div className="flex gap-2">
            {tab === "edit" && (
              <Button variant="outline" size="sm" onClick={handleSave}>
                <Save className="h-4 w-4" /> Save
              </Button>
            )}
            <Button size="sm" onClick={handleDownload} className="bg-gradient-primary text-primary-foreground hover:opacity-95">
              <Download className="h-4 w-4" /> Download PDF
            </Button>
          </div>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
