import type { Job, Profile, Preferences } from "./types";

export const SAMPLE_JOBS: Job[] = [
  {
    id: "j-001",
    title: "Senior Frontend Engineer",
    company: "Northwind Labs",
    location: "Berlin, Germany",
    workMode: "remote",
    jobType: "full-time",
    salaryMin: 75000,
    salaryMax: 95000,
    salaryCurrency: "EUR",
    description:
      "Northwind Labs is a climate-tech startup building tools for industrial decarbonization. We're looking for a Senior Frontend Engineer to lead the architecture of our customer dashboard.",
    requirements: ["5+ years React", "TypeScript", "State management (Redux/Zustand)", "Testing (Vitest/Playwright)"],
    responsibilities: [
      "Lead frontend architecture for the customer dashboard",
      "Mentor 2 junior engineers",
      "Collaborate with design on a new design system",
    ],
    niceToHave: ["Climate-tech background", "GraphQL", "D3 / data visualization"],
    applyUrl: "https://example.com/apply/northwind",
    source: "Sample",
    postedAt: new Date(Date.now() - 2 * 86400000).toISOString(),
    tags: ["React", "TypeScript", "Remote", "Climate"],
  },
  {
    id: "j-002",
    title: "Full-Stack Engineer",
    company: "Lumio",
    location: "Remote (EU)",
    workMode: "remote",
    jobType: "full-time",
    salaryMin: 65000,
    salaryMax: 85000,
    salaryCurrency: "EUR",
    description:
      "Lumio is rebuilding the workflow tools that financial advisors love. Join an early team with strong product DNA.",
    requirements: ["TypeScript end-to-end", "Node.js", "Postgres", "React"],
    responsibilities: ["Ship features end-to-end", "Own a product surface", "Pair with design"],
    applyUrl: "https://example.com/apply/lumio",
    source: "Sample",
    postedAt: new Date(Date.now() - 5 * 86400000).toISOString(),
    tags: ["TypeScript", "Node", "Postgres", "Remote"],
  },
  {
    id: "j-003",
    title: "Product Designer",
    company: "Stride",
    location: "London, UK",
    workMode: "hybrid",
    jobType: "full-time",
    salaryMin: 60000,
    salaryMax: 80000,
    salaryCurrency: "GBP",
    description:
      "Stride builds running coaching software used by 200k athletes. Help us redesign the training-plan experience.",
    requirements: ["4+ years product design", "Figma mastery", "Prototyping", "Strong portfolio"],
    responsibilities: ["Own end-to-end design for training plans", "Run user research", "Define interaction patterns"],
    applyUrl: "https://example.com/apply/stride",
    source: "Sample",
    postedAt: new Date(Date.now() - 1 * 86400000).toISOString(),
    tags: ["Design", "Figma", "Hybrid"],
  },
  {
    id: "j-004",
    title: "Backend Engineer (Go)",
    company: "Helio",
    location: "Amsterdam, NL",
    workMode: "hybrid",
    jobType: "full-time",
    salaryMin: 70000,
    salaryMax: 90000,
    salaryCurrency: "EUR",
    description:
      "Helio runs payment infrastructure for SaaS. We're scaling our platform team and looking for a backend engineer with deep Go experience.",
    requirements: ["Go 3+ years", "Postgres / event sourcing", "Distributed systems", "Kubernetes basics"],
    responsibilities: ["Build payment-routing services", "Design schemas", "On-call rotation"],
    applyUrl: "https://example.com/apply/helio",
    source: "Sample",
    postedAt: new Date(Date.now() - 7 * 86400000).toISOString(),
    tags: ["Go", "Backend", "Payments"],
  },
  {
    id: "j-005",
    title: "Data Scientist",
    company: "Atlas Health",
    location: "Boston, MA, USA",
    workMode: "onsite",
    jobType: "full-time",
    salaryMin: 130000,
    salaryMax: 165000,
    salaryCurrency: "USD",
    description:
      "Join Atlas Health's clinical analytics team to build models that improve patient outcomes in oncology.",
    requirements: ["Python", "Statistics / ML fundamentals", "SQL", "Healthcare domain a plus"],
    responsibilities: ["Build prediction models", "Translate research into shipping ML", "Collaborate with clinicians"],
    applyUrl: "https://example.com/apply/atlas",
    source: "Sample",
    postedAt: new Date(Date.now() - 3 * 86400000).toISOString(),
    tags: ["Python", "ML", "Healthcare"],
  },
  {
    id: "j-006",
    title: "Engineering Manager — Platform",
    company: "Cobalt",
    location: "Remote (Global)",
    workMode: "remote",
    jobType: "full-time",
    salaryMin: 150000,
    salaryMax: 190000,
    salaryCurrency: "USD",
    description:
      "Cobalt builds open-source infrastructure used by 30k engineering teams. Lead our platform team of 6 engineers.",
    requirements: ["3+ years engineering management", "Hands-on coding background", "Remote-first leadership"],
    responsibilities: ["Grow the platform team", "Define quarterly roadmaps", "1:1s and growth"],
    applyUrl: "https://example.com/apply/cobalt",
    source: "Sample",
    postedAt: new Date(Date.now() - 4 * 86400000).toISOString(),
    tags: ["Management", "Platform", "Remote"],
  },
  {
    id: "j-007",
    title: "Junior Frontend Developer",
    company: "Kite & Co.",
    location: "Lisbon, Portugal",
    workMode: "hybrid",
    jobType: "full-time",
    salaryMin: 28000,
    salaryMax: 36000,
    salaryCurrency: "EUR",
    description:
      "Boutique product studio looking for a junior frontend developer to grow with us across client projects.",
    requirements: ["1+ year React", "HTML/CSS", "Git", "Eagerness to learn"],
    responsibilities: ["Build UI features", "Pair with senior engineers", "Contribute to design system"],
    applyUrl: "https://example.com/apply/kite",
    source: "Sample",
    postedAt: new Date(Date.now() - 6 * 86400000).toISOString(),
    tags: ["React", "Junior", "Studio"],
  },
  {
    id: "j-008",
    title: "DevOps Engineer",
    company: "Pinecone Cloud",
    location: "Remote (US)",
    workMode: "remote",
    jobType: "full-time",
    salaryMin: 130000,
    salaryMax: 170000,
    salaryCurrency: "USD",
    description:
      "Help us run a multi-region Kubernetes platform serving billions of vector queries per day.",
    requirements: ["Kubernetes", "Terraform", "AWS or GCP", "Observability"],
    responsibilities: ["Own infra reliability", "Improve deploy pipelines", "On-call rotation"],
    applyUrl: "https://example.com/apply/pinecone",
    source: "Sample",
    postedAt: new Date(Date.now() - 8 * 86400000).toISOString(),
    tags: ["Kubernetes", "DevOps", "Remote"],
  },
  {
    id: "j-009",
    title: "AI Product Engineer",
    company: "Loop AI",
    location: "San Francisco, CA, USA",
    workMode: "hybrid",
    jobType: "full-time",
    salaryMin: 160000,
    salaryMax: 210000,
    salaryCurrency: "USD",
    description:
      "Build AI-powered workflow products used by Fortune 500 sales teams. Strong product instincts required.",
    requirements: ["TypeScript", "LLM application experience", "RAG / vector DBs", "Product sense"],
    responsibilities: ["Prototype rapidly", "Ship to production", "Talk to customers weekly"],
    applyUrl: "https://example.com/apply/loop",
    source: "Sample",
    postedAt: new Date(Date.now() - 1 * 86400000).toISOString(),
    tags: ["AI", "LLM", "TypeScript"],
  },
  {
    id: "j-010",
    title: "Mobile Engineer (iOS)",
    company: "Tempo",
    location: "Stockholm, Sweden",
    workMode: "onsite",
    jobType: "full-time",
    salaryMin: 55000,
    salaryMax: 72000,
    salaryCurrency: "EUR",
    description: "Tempo builds the music app loved by independent artists. Join our 4-person iOS team.",
    requirements: ["Swift / SwiftUI", "3+ years iOS", "Audio APIs a plus"],
    responsibilities: ["Ship iOS features", "Profile and optimize", "Collaborate with backend"],
    applyUrl: "https://example.com/apply/tempo",
    source: "Sample",
    postedAt: new Date(Date.now() - 9 * 86400000).toISOString(),
    tags: ["iOS", "Swift", "Music"],
  },
  {
    id: "j-011",
    title: "Growth Marketing Lead",
    company: "Northwind Labs",
    location: "Remote (EU)",
    workMode: "remote",
    jobType: "full-time",
    salaryMin: 65000,
    salaryMax: 85000,
    salaryCurrency: "EUR",
    description: "Lead growth experiments across paid, content, and product-led channels.",
    requirements: ["B2B SaaS growth experience", "SQL comfort", "Strong writing"],
    responsibilities: ["Run weekly experiments", "Own activation funnel", "Hire 1-2 people in year 1"],
    applyUrl: "https://example.com/apply/northwind-growth",
    source: "Sample",
    postedAt: new Date(Date.now() - 11 * 86400000).toISOString(),
    tags: ["Growth", "B2B", "Remote"],
  },
  {
    id: "j-012",
    title: "Staff Software Engineer",
    company: "Ledger",
    location: "Paris, France",
    workMode: "hybrid",
    jobType: "full-time",
    salaryMin: 110000,
    salaryMax: 150000,
    salaryCurrency: "EUR",
    description: "Architect critical security infrastructure for the most trusted hardware wallet.",
    requirements: ["8+ years engineering", "Cryptography knowledge", "Rust or C++"],
    responsibilities: ["Tech leadership across 3 teams", "Architect new platform", "Mentor staff+ track"],
    applyUrl: "https://example.com/apply/ledger",
    source: "Sample",
    postedAt: new Date(Date.now() - 12 * 86400000).toISOString(),
    tags: ["Staff", "Crypto", "Security"],
  },
  {
    id: "j-013",
    title: "Frontend Engineer — Design Systems",
    company: "Vercel",
    location: "Remote (Global)",
    workMode: "remote",
    jobType: "full-time",
    salaryMin: 130000,
    salaryMax: 175000,
    salaryCurrency: "USD",
    description: "Help build and maintain the design system that powers Vercel's products.",
    requirements: ["React", "TypeScript", "Accessibility expertise", "Component library experience"],
    responsibilities: ["Own primitives layer", "Ensure WCAG AA", "Document patterns"],
    applyUrl: "https://example.com/apply/vercel",
    source: "Sample",
    postedAt: new Date(Date.now() - 2 * 86400000).toISOString(),
    tags: ["React", "Design Systems", "A11y", "Remote"],
  },
  {
    id: "j-014",
    title: "QA Automation Engineer",
    company: "Helio",
    location: "Remote (EU)",
    workMode: "remote",
    jobType: "contract",
    salaryMin: 50000,
    salaryMax: 70000,
    salaryCurrency: "EUR",
    description: "6-month contract to set up our end-to-end test infrastructure.",
    requirements: ["Playwright or Cypress", "TypeScript", "CI/CD"],
    responsibilities: ["Build E2E suite", "Integrate into CI", "Train the team"],
    applyUrl: "https://example.com/apply/helio-qa",
    source: "Sample",
    postedAt: new Date(Date.now() - 4 * 86400000).toISOString(),
    tags: ["QA", "Playwright", "Contract"],
  },
  {
    id: "j-015",
    title: "Software Engineering Intern",
    company: "Stride",
    location: "London, UK",
    workMode: "hybrid",
    jobType: "internship",
    salaryMin: 30000,
    salaryMax: 36000,
    salaryCurrency: "GBP",
    description: "12-week summer internship on the Stride mobile team.",
    requirements: ["CS undergraduate", "Some React Native or Swift", "Curiosity"],
    responsibilities: ["Ship a feature", "Pair with mentor", "Present at end-of-internship demo"],
    applyUrl: "https://example.com/apply/stride-intern",
    source: "Sample",
    postedAt: new Date(Date.now() - 1 * 86400000).toISOString(),
    tags: ["Internship", "Mobile"],
  },
  {
    id: "j-016",
    title: "Senior Backend Engineer (Python)",
    company: "Atlas Health",
    location: "Remote (US)",
    workMode: "remote",
    jobType: "full-time",
    salaryMin: 150000,
    salaryMax: 190000,
    salaryCurrency: "USD",
    description: "Architect FastAPI services powering clinical workflows used in 80+ hospitals.",
    requirements: ["Python (FastAPI/Django)", "Postgres", "AWS", "HIPAA-compliant systems"],
    responsibilities: ["Lead service design", "Mentor 3 engineers", "Drive technical decisions"],
    applyUrl: "https://example.com/apply/atlas-be",
    source: "Sample",
    postedAt: new Date(Date.now() - 6 * 86400000).toISOString(),
    tags: ["Python", "FastAPI", "Healthcare", "Remote"],
  },
  {
    id: "j-017",
    title: "Customer Success Engineer",
    company: "Loop AI",
    location: "Remote (US)",
    workMode: "remote",
    jobType: "full-time",
    salaryMin: 110000,
    salaryMax: 140000,
    salaryCurrency: "USD",
    description: "Be the technical bridge between our customers and product team.",
    requirements: ["Hands-on coding", "Customer-facing experience", "API integrations"],
    responsibilities: ["Onboard enterprise customers", "Build sample integrations", "Feed insights back to product"],
    applyUrl: "https://example.com/apply/loop-cse",
    source: "Sample",
    postedAt: new Date(Date.now() - 3 * 86400000).toISOString(),
    tags: ["Customer Success", "API", "Remote"],
  },
  {
    id: "j-018",
    title: "Lead Designer",
    company: "Cobalt",
    location: "Remote (Global)",
    workMode: "remote",
    jobType: "full-time",
    salaryMin: 130000,
    salaryMax: 165000,
    salaryCurrency: "USD",
    description: "Set the design direction for Cobalt's developer-facing products.",
    requirements: ["7+ years product design", "Developer tool experience", "Systems thinking"],
    responsibilities: ["Lead a team of 3 designers", "Own visual + interaction systems", "Partner with EM and PM"],
    applyUrl: "https://example.com/apply/cobalt-design",
    source: "Sample",
    postedAt: new Date(Date.now() - 5 * 86400000).toISOString(),
    tags: ["Design", "Lead", "DevTools"],
  },
  {
    id: "j-019",
    title: "Site Reliability Engineer",
    company: "Vercel",
    location: "Remote (Global)",
    workMode: "remote",
    jobType: "full-time",
    salaryMin: 145000,
    salaryMax: 185000,
    salaryCurrency: "USD",
    description: "Keep Vercel's edge network humming for millions of deployments.",
    requirements: ["SRE experience at scale", "Linux internals", "Observability tooling"],
    responsibilities: ["Improve uptime", "Run incident reviews", "Build reliability tooling"],
    applyUrl: "https://example.com/apply/vercel-sre",
    source: "Sample",
    postedAt: new Date(Date.now() - 7 * 86400000).toISOString(),
    tags: ["SRE", "Edge", "Remote"],
  },
  {
    id: "j-020",
    title: "Technical Writer",
    company: "Pinecone Cloud",
    location: "Remote (Global)",
    workMode: "remote",
    jobType: "full-time",
    salaryMin: 90000,
    salaryMax: 120000,
    salaryCurrency: "USD",
    description: "Write the docs that make vector databases approachable to all developers.",
    requirements: ["Technical writing portfolio", "Comfort reading code", "Markdown / static site generators"],
    responsibilities: ["Own docs roadmap", "Pair with engineers on releases", "Write tutorials"],
    applyUrl: "https://example.com/apply/pinecone-docs",
    source: "Sample",
    postedAt: new Date(Date.now() - 10 * 86400000).toISOString(),
    tags: ["Docs", "Writing", "Remote"],
  },
];

export const SAMPLE_PROFILE: Profile = {
  fullName: "Alex Rivera",
  email: "alex.rivera@example.com",
  phone: "+1 555 010 4567",
  location: "Berlin, Germany",
  headline: "Senior Frontend Engineer • React • Design Systems",
  summary:
    "Frontend engineer with 6+ years building production web apps. Led the design system at a Series B fintech and shipped a customer-facing dashboard from zero to 50k MAUs. Comfortable across the stack and known for clean architecture and steady mentorship.",
  workHistory: [
    {
      id: "w-1",
      company: "Brightside Finance",
      role: "Senior Frontend Engineer",
      startDate: "2022-03",
      endDate: null,
      location: "Berlin (Remote)",
      achievements: [
        "Led migration of legacy Angular app to React + TypeScript, cutting bundle size by 38%",
        "Built and shipped the company-wide design system (40+ components, full a11y coverage)",
        "Mentored 3 junior engineers; 2 promoted to mid-level within 18 months",
      ],
    },
    {
      id: "w-2",
      company: "Kindred Studio",
      role: "Frontend Engineer",
      startDate: "2019-08",
      endDate: "2022-02",
      location: "Lisbon, Portugal",
      achievements: [
        "Delivered 14 client projects across e-commerce, SaaS, and editorial verticals",
        "Built reusable Next.js starter that became the studio's default for new projects",
      ],
    },
  ],
  education: [
    {
      id: "e-1",
      school: "University of Lisbon",
      degree: "B.Sc.",
      field: "Computer Science",
      startDate: "2015-09",
      endDate: "2019-06",
    },
  ],
  skills: [
    "React", "TypeScript", "Next.js", "Tailwind CSS", "Design Systems",
    "Accessibility", "Vitest", "Playwright", "Node.js", "Postgres",
    "Figma", "Mentorship", "Performance",
  ],
};

export const SAMPLE_PREFERENCES: Preferences = {
  desiredRoles: ["Senior Frontend Engineer", "Staff Frontend Engineer", "Tech Lead"],
  locations: ["Berlin", "Remote (EU)", "Remote (Global)"],
  workModes: ["remote", "hybrid"],
  salaryMin: 80000,
  salaryCurrency: "EUR",
  jobTypes: ["full-time"],
};
